# Generated by Django 5.1.4 on 2024-12-19 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('hora_inscripcion', models.TimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('completada', 'Completada'), ('anulada', 'Anulada'), ('no_asisten', 'No Asisten')], max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('cantidad_personas', models.PositiveIntegerField()),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscritos', to='seminario.institucion')),
            ],
        ),
    ]
